#!/bin/bash
################################################################################
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
################################################################################
# prerequisites
# apt-get install -y libapache2-mod-perl2 libapache2-mod-scgi              \
#                    libapache2-mod-php5 php5-cgi libbsd-resource-perl     \
#                    libdevel-symdump-perl                                 \
#                    libdigest-hmac-perl libapache2-mod-perl2 liburi-perl  \
#                    libdigest-sha1-perl  libhtml-parser-perl              \
#                    libapache2-mod-perl2 libxml-parser-perl               \
#                    xauth x11-apps dh-make-perl unzip par2 unrar          \
#                    python python-support python-cheetah python-configobj \
#                    python-feedparser python-yenc python-openssl          \
#                    php5 php5-sqlite pkg-config

ENV_VARS=(IPREDATOR_USERNAME IPREDATOR_PASSWORD LDAP_USERNAME LDAP_PASSWORD DOMAIN BASEURL S3KEY S3SECRET S3ROBUCKET S3RWBUCKET DDNS_LOGIN DDNS_PASSWORD DDNS_DOMAIN NZBMATRIX_LOGIN NZBMATRIX_APIKEY ASTRAWEB_LOGIN ASTRAWEB_PASSWORD SABNZBD_APIKEY MEDIACAS_HOSTNAME)

clear;
EXIT=0
for idx in `seq 0 $(expr ${#ENV_VARS[@]} - 1)`;do
    VAL=$(set | grep "^${ENV_VARS[${idx}]}="|sed -e's/[^=]*=//';)
    if [ -z "${VAL}" ]; then 
        echo "${ENV_VARS[${idx}]} not set"
        EXIT=1
    fi
done
export BASEDN="dc=$(echo ${DOMAIN}|sed -e's/\./,dc=/g')"
export CREDENTIALS="${LDAP_USERNAME}:${LDAP_PASSWORD}"
exit ${EXIT}
