#!/bin/bash
################################################################################
apt-get install -y python python-support python-cheetah python-configobj      \
                   python-feedparser python-yenc python-openssl unzip par2    \
                   unrar xauth x11-apps
################################################################################
# sabnzbd
[ ! -d /opt/local ] && mkdir /opt/local 
(cd /opt/local; wget -O SABnzbd-0.5.6-src.tar.gz "http://downloads.sourceforge.net/project/sabnzbdplus/sabnzbdplus/sabnzbd-0.5.6/SABnzbd-0.5.6-src.tar.gz")
(cd /opt/local; tar xvzf SABnzbd-0.5.6-src.tar.gz)
( cd /etc/apache2/mods-enabled; [ ! -h proxy.load ] && ln -s ../mods-available/proxy.load )
( cd /etc/apache2/mods-enabled; [ ! -h proxy_http.load ] && ln -s ../mods-available/proxy_http.load )
( cd /etc/apache2/mods-enabled; [ ! -h proxy.conf ] && ln -s ../mods-available/proxy.conf )

su - opt whoami >/dev/null 2>&1
[ ! -d /home/opt/downloads ] && mkdir -p /home/opt/downloads
[ ! -d /home/opt/downloads/incomplete ] && mkdir -p /home/opt/downloads/incomplete
if [ -d /home/opt/downloads/complete ] ;then
   rmdir /home/opt/downloads/complete
   ln -s /opt/event_correlation/data/complete /home/opt/downloads/complete
fi
chown -R opt:users /home/opt/downloads

[ ! -d /home/opt/.sabnzbd ] && mkdir -p /home/opt/.sabnzbd
cat<<EOF > /home/opt/.sabnzbd/sabnzbd.ini
__version__ = 18
[misc]
queue_complete = ""
https_port = 9090
folder_rename = 1
allow_64bit_tools = 1
rss_rate = 60
https_key = server.key
cleanup_list = ,
cache_limit = ""
par_option = ""
web_color = white
replace_spaces = 0
web_color2 = ""
dirscan_speed = 5
enable_filejoin = 1
create_group_folders = 0
api_key = ${SABNZBD_APIKEY}
no_penalties = 0
bandwidth_limit = 0
dirscan_dir = nzb/loading
disable_api_key = 0
email_to = ,
password = ""
permissions = ""
auto_disconnect = 1
enable_date_sorting = 0
replace_dots = 0
movie_sort_extra = -cd%1
ionice = ""
enable_unzip = 1
download_free = ""
port = 8080
email_dir = ""
email_full = 0
log_dir = logs
admin_dir = admin
nzb_backup_dir = ""
tv_sort_countries = 1
date_categories = tv,
ssl_type = v23
date_sort_string = ""
schedlines = ,
host = localhost
ignore_samples = 0
enable_tsjoin = 1
auto_browser = 0
pause_on_post_processing = 0
enable_unrar = 1
email_account = ""
email_server = ""
config_lock = 0
api_warnings = 1
tv_sort_string = ""
dirscan_priority = 0
username = ""
download_dir = downloads/incomplete
size_limit = ""
enable_par_cleanup = 1
safe_postproc = 1
cache_dir = cache
complete_dir = downloads/complete
replace_illegal = 1
par2_multicore = 0
warned_old_queue = 0
language = us-en
check_new_rel = 1
enable_https = 0
no_dupes = 0
top_only = 1
quick_check = 1
movie_sort_string = ""
email_from = ""
movie_extra_folder = 0
dirscan_script = None
email_endjob = 0
tv_categories = ,
unpack_check = 1
login_realm = SABnzbd
send_group = 0
refresh_rate = 0
movie_categories = movies,
script_dir = ""
email_pwd = ""
ignore_wrong_unrar = 0
nice = ""
enable_movie_sorting = 0
https_cert = server.cert
web_dir2 = ""
fail_on_crc = 0
auto_sort = 0
dirscan_opts = 3
web_dir = smpl
queue_complete_pers = 0
enable_tv_sorting = 0
folder_max_length = 256
[logging]
max_log_size = 5242880
log_level = 1
log_backups = 5
enable_cherrypy_logging = 0
[newzbin]
username = ""
https = 1
bookmark_rate = 60
bookmarks = 0
password = ""
unbookmark = 1
[nzbmatrix]
username = ${NZBMATRIX_LOGIN}
apikey = ${NZBMATRIX_APIKEY}
[categories]
[[misc]]
priority = -100
pp = ""
name = misc
script = Default
newzbin = Misc
dir = Misc
[[tv]]
priority = -100
pp = ""
name = tv
script = Default
newzbin = TV
dir = TV
[[unknown]]
priority = -100
pp = ""
name = unknown
script = Default
newzbin = Unknown
dir = Unknown
[[resources]]
priority = -100
pp = ""
name = resources
script = Default
newzbin = Resources
dir = Resources
[[apps]]
priority = -100
pp = ""
name = apps
script = Default
newzbin = Apps
dir = Apps
[[movies]]
priority = -100
pp = ""
name = movies
script = Default
newzbin = Movies
dir = Movies
[[consoles]]
priority = -100
pp = ""
name = consoles
script = Default
newzbin = Consoles
dir = Consoles
[[books]]
priority = -100
pp = ""
name = books
script = Default
newzbin = Books
dir = Books
[[games]]
priority = -100
pp = ""
name = games
script = Default
newzbin = Games
dir = Games
[[anime]]
priority = -100
pp = ""
name = anime
script = Default
newzbin = Anime
dir = Anime
[[music]]
priority = -100
pp = ""
name = music
script = Default
newzbin = Music
dir = Music
[[pda]]
priority = -100
pp = ""
name = pda
script = Default
newzbin = PDA
dir = PDA
[[emulation]]
priority = -100
pp = ""
name = emulation
script = Default
newzbin = Emulation
dir = Emulation
[servers]
[[ssl.astraweb.com:563]]
username = ${ASTRAWEB_LOGIN}
enable = 1
name = ssl.astraweb.com:563
fillserver = 0
connections = 20
ssl = 1
host = ssl.astraweb.com
timeout = 120
password = ${ASTRAWEB_PASSWORD}
optional = 0
port = 563
EOF
chown -R opt:users /home/opt/.sabnzbd

# /usr/bin/python /opt/local/SABnzbd-0.5.6/SABnzbd.py 
exit 0;
