#!/bin/bash
################################################################################
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
################################################################################
spinner(){
    PROC=$1
    while [ -d /proc/$PROC ];do
        echo -ne '/\x08' ; sleep 0.05
        echo -ne '-\x08' ; sleep 0.05
        echo -ne '\\\x08' ; sleep 0.05
        echo -ne '|\x08' ; sleep 0.05
    done
    return 0
}

DIR=$(dirname $0)
install -m 0755 ${DIR}/00_credentials /usr/local/sbin
install -m 0755 ${DIR}/01_loopdevs /usr/local/sbin
install -m 0755 ${DIR}/02_vpn /usr/local/sbin
install -m 0755 ${DIR}/03_rtorrent /usr/local/sbin
install -m 0755 ${DIR}/04_apache /usr/local/sbin
install -m 0755 ${DIR}/05_wtorrent /usr/local/sbin
install -m 0755 ${DIR}/06_sabnzbd /usr/local/sbin
install -m 0755 ${DIR}/07_sickbeard /usr/local/sbin
install -m 0755 ${DIR}/08_screen /usr/local/sbin
install -m 0755 ${DIR}/re_up /usr/local/sbin


for script in 00_credentials 01_loopdevs 02_vpn 03_rtorrent 04_apache 05_wtorrent 06_sabnzbd 07_sickbeard; do
    echo -n "Running ${script}: "
    /usr/local/sbin/${script} > /var/log/${script}.log 2>&1 &
    spinner $!
    if [ $? -eq 0 ]; then
        if [ -f "/usr/local/sbin/${script}" ]; then rm "/usr/local/sbin/${script}"; fi
        #if [ -f "/var/log/${script}.log" ]; then rm "/var/log/${script}.log"; fi
        echo "OK"
    else
        echo "FAIL"
        echo "something went wrong with ${script}. Not willing to continue."
        echo "Check /var/log/${script}.log for details"
        exit 1;
    fi
done
/usr/local/sbin/08_screen > /var/log/08_screen.log 2>&1 # doesn't seem to want to run in the background

echo "installing re_up into root's crontab"
cat<<EOF>/root/.crontab
*/5 * * * * /usr/local/sbin/re_up > /dev/null 2>&1
EOF
crontab /root/.crontab
echo "finished."
