#!/bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
DGW=$(/sbin/route -n|/bin/grep "^0.0.0.0"|/usr/bin/awk '{print $2}')
if [ ! -z "${DGW}" ]; then
    /bin/ping -w3 -c 3 ${DGW} > /dev/null 2>&1 && exit
fi
IP=$(/sbin/ifconfig ppp0|/bin/grep inet|/bin/sed -e's/[^:]*://' -e's/ .*//')
while [ -z "${IP}" ];do
    ps -ef | grep pptp -q || pon  ipredator
    sleep 20
    ifconfig ppp0
    EXIT=$?
    while [ "${EXIT}" -eq "1" ]; do
        ifconfig ppp0
        EXIT=$?
        sleep 3
    done
    IP=$(/sbin/ifconfig ppp0|/bin/grep inet|/bin/sed -e's/[^:]*://' -e's/ .*//')
done

# Fix our default route...
route del default
EXIT=$?
while [ ${EXIT} -ne 7 ]; do
    route del default
done

export IPADDRESS=$(/sbin/ifconfig ppp0 | grep inet|sed -e's/[^:]*://' -e's/ .*//')
if [ ! -z "${IPADDRESS}" ]; then
    export HOSTNEW=$(/usr/bin/dig +short -x ${IPADDRESS}|sed -e 's/\.$//g')
    if [ ! -z "${HOSTNEW}" ]; then
        sed -e"s/\[% IPADDRESS %\]/${IPADDRESS}/"  -e"s/\[% HOSTNEW %\]/${HOSTNEW}/" \
           /opt/event_correlation/etc/rtorrent.rc.tpl > /home/opt/.rtorrent.rc
        chown -h opt:users /home/opt/.rtorrent.rc
        PROCESS=$(ps -ef | grep event_l[o]op| awk '{print $2}')
        # HUP terminates the process outright, violates the principle of least surprise (it should re-load it's config).
        [ ! -z "${PROCESS}" ] && kill -1 ${PROCESS}
        /bin/hostname ${HOSTNEW}
    fi
fi
route add default gw ${IP}

IP=$(/sbin/ifconfig ppp0|/bin/grep inet|/bin/sed -e's/[^:]*://' -e's/ .*//')
cat<<EOF >/etc/shorewall/rules
ACCEPT net \$FW:${IP} tcp 22
ACCEPT net \$FW:${IP} tcp 444
#ACCEPT net \$FW:${IP} tcp tcp 6800:6899
EOF
for ns in $(dig +short -t ns ${DOMAIN}); do echo "ACCEPT net:$(dig +short $ns) all" >> /etc/shorewall/rules; done
/etc/init.d/shorewall restart
/usr/sbin/ddclient
