#!/bin/bash
################################################################################
# This is just a proof of concept. It's not really useful to anyone but me; 
# But I didn't want to lose it, so I put it in teh githubz
# It assumes that you have:
#
#   1) a VPS running debian 5.0.7 (lenny) with autofs4 and autodir installed
#   2) an iPredator account 
#   3) a dyndns account and domain name
#   4) an Amazon AWS Account with S3 Credentials 
#   5) an LDAP Server with user accounts on it  (for apache access)
#   6) a NZBMatrix account
#   7) an Astraweb.com NNTP account

################################################################################
# The following environment variables installed in your shell 
# (prior to running install, or the credentials check will fail)
#
# IPREDATOR_USERNAME  -- Your iPredator username
# IPREDATOR_PASSWORD  -- Your iPredator password
#
# S3KEY               -- Amazon s3 key
# S3SECRET            -- Amazon s3 secret
# S3ROBUCKET          -- A read-only bucket in s3
# S3RWBUCKET          -- A read-write bucket in s3
#
# LDAP_USERNAME       -- An LDAP user that may read/write the CAS
# LDAP_PASSWORD       -- The read/write user's password
#
# LDAP_ANON_BIND      -- The LDAP URI for account lookups
# LDAP_ANON_USER      -- A user that may bind and look up usernames
# LDAP_ANON_PASS      -- that user's password
#
# DOMAIN              -- The domain whose NS records wil be allowed non-vpn traffic
# BASEURL             -- The CAS base URL
# MEDIACAS_HOSTNAME   -- The hostname you push, pull data to, from your CAS
#
# DDNS_LOGIN          -- Your DynDNS login
# DDNS_PASSWORD       -- Your DynDNS password
# DDNS_DOMAIN         -- Your DynDNS hostname
#
# NZBMATRIX_LOGIN     -- Your NZBMatrix login
# NZBMATRIX_APIKEY    -- Your NZBMatrix API Key
#
# ASTRAWEB_LOGIN      -- Your AstraWeb password
# ASTRAWEB_PASSWORD   -- Your AstraWeb password
#
# SABNZBD_APIKEY      -- Your Sabnzbd api key 
#
################################################################################
export TMP=$(mktemp -d /tmp/SMEGFLIX.XXXX)
[ -d "${TMP}" ] && ( cd ${TMP}; git clone git://github.com/fapestniegd/smegflix.git smegflix )
if [ -x "${TMP}/smegflix/install" ] ;then 
    ${TMP}/smegflix/install
    [ -d "${TMP}" ] && rm -fr "${TMP}"
fi
