#!/bin/bash
################################################################################
# This is just a proof of concept. It's not really useful to anyone but me. but I didn't want to lose it.
################################################################################
export TMP=$(mktemp -d /tmp/SMEGFLIX.XXXX)
[ -d "${TMP}" ] && ( cd ${TMP}; git clone git://github.com/fapestniegd/smegflix.git )
if [ -x "${TMP}/smegflix/install" ] ;then 
    ( cd ${TMP}; git clone git://github.com/fapestniegd/smegflix.git )
    [ -d "${TMP}" ] && rm -fr "${TMP}"
fi
